### ISSUE TITLE
Parent/child check is not enough

### ISSUE THREAD

**Issue by pepelsbey** [MananTank/validate-html-nesting#7]
Unfortunately, it’s not enough to check parent/child to avoid DOM modification in the browser.

For example:

1. `p > a` is fine

```html
<p>
    Another reason to
    <a href="">validate</a>
    your markup.
</p>
```

2. `a > p` is fine, too

```html
<a href="">
    <p>
        Another reason to
        validate
        your markup.
    </p>
</a>
```

3. But once you have `a > p > a`

```html
<a href="">
    <p>
        Another reason to
        <a href="">validate</a>
        your markup.
    </p>
</a>
```

Everything goes sideways:

```html
<a href=""></a>
<p>
    <a href="">Another reason to </a>
    <a href="">validate</a>
    your markup.
</p>
```

I wonder if adding a third parameter or accepting a string with a DOM subtree would be a viable option.

**Comment by MananTank** [comment]
You can catch these errors by calling the validator for each descendant of a parent element. 

which means that for your example, validator will catch the invalid nesting of anchor inside an anchor element
